### PR TITLE
updated plugin and deps to grails 4.0.0

### PR DESCRIPTION
**Pull request by animator013**
An upgrade to grails 4, gradle 5.

Had to remove CompileStatic annotation from GrailsShiroRealm. That needs a further look why it won't compile.

This is a WIP.

### CODE REVIEW

**Comment by animator013** [comment]
LDAP users always fails for me, seems they don't exist. Can you help me with this ?

**Comment by animator013** [comment]
Please have a look. I think this is ready except that CompileStatic. That is weird why it does not work. Maybe new groovy version introduced some kind of bug.

**Comment by pmcneil** [comment]
will do. Just trying to see what the best way to support multiple grails versions is - especially on the plugin publishing side of things. We'll need a Grails 3 support branch.

**Comment by pmcneil** [comment]
I have pulled this down and am checking it out - I'm having a couple of issues:
* The tests aren't actually working
* It seems to get the repository version of the plugin, not the local (adding mavenLocal() to build.gradle in the tests fix that)
* We probably need to move to using the grailsw to run the test apps (thus avoiding the sdkman install)

Anyway just thought I'd let you know I'm working through it - thanks

**Comment by animator013** [comment]
I ran the tests fine also travis runs it without a problem. Not sure how you meant this. I only changed travis to use local distribution of gradle not the global one on the PATH.

**Comment by pmcneil** [comment]
It's OK I have fixed a couple of small things I found - so the real issue was that the test apps were picking up the plugin jar form the Bintray repo, not the locally built one - so the tests were passing (seems the grails 3 version plugin can work in grails 4?) ... anyway I'll be pushing up my changes and we'll publish a grails 4 version soon. Just looking at the best way to do it (and keep the grails 3 version being updated for a while)

**Comment by animator013** [comment]
Yes it seemed the plugin somehow worked but I think it is proper to upgrade all the dependencies to avoid any future problems which can rise from grails 3 deps.

**Comment by pmcneil** [comment]
I have merged this into master with some changes. There is now a Grails-3 branch for backporting changes to the grails 3 plugin.

**Pull request closed without merging**
